name: Android CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JAVA_TOOL_OPTIONS: -Xmx4g

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}
          restore-keys: gradle-
      
      - name: Build project
        run: ./gradlew app:assembleDebug

  instrumented-tests:
    name: "Instrumented Tests"
    timeout-minutes: 30
    runs-on: macos-latest
    steps:
      - name: "Checkout Branch"
        uses: actions/checkout@v2
      - name: "Install JDK 11"
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - name: "Run Instrumented Tests"
        uses: reactivecircus/android-emulator-runner@v2.20.0
        with:
          api-level: 29
          script: ./gradlew :android-core:cAT :android-kit-base:cAT --stacktrace
      - name: "Archive Instrumented Tests Results"
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: "instrumented-tests-results"
          path: android-core/build/reports/androidTests/connected/**
