name: Android CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 
      uses: actions/setup-java@v3.1.0
      with:
        java-version: 11
        distribution: 'temurin'
        cache: gradle
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
      
 
          
          
  run-instrumented-tests:
    runs-on: macos-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3.1.0
        with:
          distribution: 'temurin'
          java-version: '11'
         
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Run instrumented tests
        uses: reactivecircus/android-emulator-runner@v2.24.0
        with:
          api-level: 29
          profile: Nexus 6
          arch: x86_64
          script: ./gradlew connectedAndroidTest
          
      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0 
        if: ${{ always() }} # IMPORTANT: run Android Test Report regardless
