name: Android CI

on: [push, pull_request]

defaults:
  run:
    working-directory: wovie

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 
      uses: actions/setup-java@v3.1.0
      with:
        java-version: 11
        distribution: 'temurin'
        cache: gradle
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
      
 
          
          
  run-instrumented-tests:
    runs-on: macos-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3.1.0
        with:
          distribution: 'temurin'
          java-version: '11'
         
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Run instrumented tests
        uses: reactivecircus/android-emulator-runner@v2.24.0
        with:
          api-level: 29
          profile: Nexus 6
          arch: x86_64
          working-directory: wovie
          script: ./gradlew connectedAndroidTest
          
      - name: Upload Test Reports Folder
        uses: actions/upload-artifact@v2
        if: ${{ always() }} # IMPORTANT: Upload reports regardless of status
        with:
          name: reports
          path: CarEshipApp/ # path to where the xml test results are stored
          
          
  report:
      runs-on: ubuntu-latest
      needs: run-instrumented-tests # The report job will run after tests job
      if: ${{ always() }} # IMPORTANT: Execute report job regardless of status
      steps:
        - name: Download Test Reports Folder
          uses: actions/download-artifact@v2
          with:
           name: reports
        - name: Android Test Report
          uses: asadmansr/android-test-report-action@v1.2.0 
          if: ${{ always() }} # IMPORTANT: run Android Test Report regardless
          #Adopted from https://github.com/asadmansr/android-test-report-action-example
