name: Android CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      name: Checkout current repository in ubuntu's file system 
      
    - uses: actions/setup-java@v1
      name: Setup JDK 1.8
      with:
        java-version: 1.8
    - uses: reactivecircus/android-emulator-runner@v2
      name: Run instrumentation tests
      with:
        api-level: 29
        arch: x86
        profile: Nexus 6
        avd-name: test
        emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -camera-back none
        disable-animations: true
        script: ./gradlew connectedCheck

      

      
