name: Build

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RELEASE_KEYSTORE_PATH: ${{ secrets.RELEASE_KEYSTORE_PATH }}
      RELEASE_KEYSTORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
      RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
      RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup gradle
      run: chmod +x ./gradlew
      
    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: caches-${{ runner.os }}-${{ hashFiles('**/*.gradle') }}
        
    - uses: actions/cache@v1
      with:
        path: ~/.gradle/wrapper
        key: wrapper-${{ runner.os }}-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
        
    - name: set up JDK 11
      uses: actions/setup-java@v1
      with:
         java-version: '11'
         distribution: 'temurin'
         cache: gradle

    - name: Build with Gradle
      run: ./gradlew check --stacktrace

  tests:
    runs-on: macos-latest
    env:
      RELEASE_KEYSTORE_PATH: ${{ secrets.RELEASE_KEYSTORE_PATH }}
      RELEASE_KEYSTORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
      RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
      RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
           java-version: '11'
           distribution: 'temurin'
           cache: gradle

      - name: Setup gradle
        run: chmod +x ./gradlew
        
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: caches-${{ runner.os }}-${{ hashFiles('**/*.gradle') }}

      - uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper
          key: wrapper-${{ runner.os }}-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Run Instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 27
          emulator-build: 7425822
          script: ./gradlew connectedCheck --stacktrace
          
          
  instrumented_tests:
    name: Run Instrumented Tests
    runs-on: macos-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: rust toolchain setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: install cargo ndk
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-ndk
      - name: setup build targets
        run: rustup target add aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android
      - name: instrumented tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: cd android/core; ./gradlew connectedAndroidTest --stacktrace
      - name: Instrumented tests results
        uses: actions/upload-artifact@v2
        with:
          name: instrumented-tests-results
          path: app/build/reports/androidTests/connected/index.html

      
